### ISSUE TITLE
请问有注销服务的功能吗

### ISSUE THREAD

**Issue by DaminZheng** [KcangYan/nacos-python-sdk#2]

**Comment by KcangYan** [comment]
没有直接注销服务的接口，不过你注册服务的时候&nbsp;选择临时实例&nbsp;想注销的话&nbsp;直接终止注册就可以相当于注销服务了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KcangYan/nacos-python-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 晚上6:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [KcangYan/nacos-python-sdk] 请问有注销服务的功能吗 (#2)





 
Closed #2.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KcangYan** [comment]
没有直接注销服务的接口，不过你注册服务的时候 选择临时实例（你不更改设置的话&nbsp;默认是注册为临时实例&nbsp;心跳断开nacos默认注销实例） 想注销的话 直接终止注册就可以相当于注销服务了




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "KcangYan/nacos-python-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 晚上6:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [KcangYan/nacos-python-sdk] 请问有注销服务的功能吗 (#2)





 
Closed #2.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
