### ISSUE TITLE
I think there is a bug in nacos.py

### ISSUE THREAD

**Issue by yuxiazff** [KcangYan/nacos-python-sdk#3]
i think  there is a bug in nacos.py, the following code:
`        if method == "GET" or method == "get":
            url = url + "/"
            for item in args:
                url = url + str(item) + "/"
            url = url[:-1]
            if kwargs.__len__() != 0:
                url = url + "?"
                for item in kwargs:
                    url = url + str(item) + "=" + str(kwargs[item]) + "&"
            return requests.get(url[:-1], timeout=self.timeout).text`

should be changed to:
        if method == "GET" or method == "get":
            url = url + "/"
            for item in args:
                url = url + str(item) + "/"
            url = url[:-1]
            if kwargs.__len__() != 0:
                url = url + "?"
                for item in kwargs:
                    url = url + str(item) + "=" + str(kwargs[item]) + "&"
                return requests.get(url[:-1], timeout=self.timeout).text
            else:
                return requests.get(url, timeout=self.timeout).text

**Comment by KcangYan** [comment]
可否给我看一下测试出来的问题？我并没有发现bug

**Comment by yuxiazff** [comment]
在请求是get请求，并且没有参数的时候，会出错。因为232行url = url[:-1]已经把url最后的/去掉了，而237行return requests.get(url[:-1], timeout=self.timeout).text又删除了最后的一个字符，所以导致路径不对了。

**Comment by KcangYan** [comment]
229行&nbsp;url = url + "/" 已经提前添加了一个 / ，不管有没有参数删除最后一个字符都是/




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KcangYan/nacos-python-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KcangYan/nacos-python-sdk] I think there is a bug in nacos.py (Issue #3)





 
在请求是get请求，并且没有参数的时候，会出错。因为232行url = url[:-1]已经把url最后的/去掉了，而237行return requests.get(url[:-1], timeout=self.timeout).text又删除了最后的一个字符，所以导致路径不对了。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuxiazff** [comment]
可是232行已经删除过一遍/了啊

**Comment by KcangYan** [comment]
我看到了 因为那个混合的get请求方法是后来加的忘记了上面的-1了。后续我会改掉更新上去的 谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KcangYan/nacos-python-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KcangYan/nacos-python-sdk] I think there is a bug in nacos.py (Issue #3)





 
可是232行已经删除过一遍/了啊
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuxiazff** [comment]
嗯嗯，不客气滴。那我就把这个问题关掉啦
